# Generated by Django 5.0.14 on 2025-08-20 04:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0147_page_content_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSiteClosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.IntegerField(choices=[(0, 'Red Warning'), (1, 'Orange Warning'), (2, 'Blue Warning'), (3, 'Green Warning')], default=0)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('active', models.BooleanField(default=True)),
                ('closure_start', models.DateTimeField()),
                ('closure_end', models.DateTimeField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
