# Generated by Django 5.2.10 on 2026-04-05 07:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0148_publicsiteclosure'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkRefundCancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_name', models.CharField(max_length=255, unique=True)),
                ('bulk_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('paused', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BulkRefundCancelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.IntegerField(choices=[(0, 'Pending Full Refund'), (1, 'Pending Partial Refund'), (2, 'Full Refund Completed'), (3, 'Partial Refund Completed'), (4, 'Full Refund Failed'), (5, 'Partial Refund Failed'), (6, 'Not Required')], default=0)),
                ('cancel_type', models.IntegerField(choices=[(0, 'Cancel Booking'), (1, 'Cancel Booking Completed'), (2, 'Not Required')], default=0)),
                ('email_type', models.IntegerField(choices=[(0, 'Cancel Booking Email'), (1, 'Cancel Booking Sent'), (2, 'Not Required')], default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bulk_refund_cancel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulkrefundcancel', to='parkstay.bulkrefundcancel')),
            ],
        ),
    ]
