# Generated by Django 5.2.10 on 2026-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0149_bulkrefundcancel_bulkrefundcancellist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrefundcancellist',
            name='booking_reference',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
