# Generated by Django 5.2.10 on 2026-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0150_bulkrefundcancellist_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrefundcancel',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
