# Generated by Django 5.2.10 on 2026-04-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0151_bulkrefundcancel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrefundcancellist',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bulkrefundcancellist',
            name='cancel_type',
            field=models.IntegerField(choices=[(0, 'Cancel Booking'), (1, 'Cancel Booking Completed'), (2, 'Not Required'), (3, 'Cancel Booking Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='bulkrefundcancellist',
            name='email_type',
            field=models.IntegerField(choices=[(0, 'Cancel Booking Email'), (1, 'Cancel Booking Sent'), (2, 'Not Required'), (3, 'Cancel Booking Email Failed')], default=0),
        ),
    ]
