# Generated by Django 5.2.10 on 2026-04-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0152_bulkrefundcancellist_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkrefundcancellist',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
